export const config = {
  port: Number(process.env.PORT ?? 4000),
  universalisBaseUrl: process.env.UNIVERSALIS_BASE_URL ?? "https://universalis.app/api/v2",
  xivapiBaseUrl: process.env.XIVAPI_BASE_URL ?? "https://v2.xivapi.com/api",
  xivapiApiKey: process.env.XIVAPI_API_KEY ?? "",
  universalisRequestsPerSecond: Number(process.env.UNIVERSALIS_REQS_PER_SECOND ?? 20),
  arbitrageRefreshMinutes: Number(process.env.ARBITRAGE_REFRESH_MINUTES ?? 15),
  marketSnapshotFreshHours: Number(process.env.MARKET_SNAPSHOT_FRESH_HOURS ?? 6),
  marketSnapshotRetentionDays: Number(process.env.MARKET_SNAPSHOT_RETENTION_DAYS ?? 14),
  marketWarningLowSaleCount: Number(process.env.MARKET_WARNING_LOW_SALE_COUNT ?? 7),
  marketWarningMinDataCenters: Number(process.env.MARKET_WARNING_MIN_DATA_CENTERS ?? 2),
  marketWarningStaleAverageHours: Number(process.env.MARKET_WARNING_STALE_AVERAGE_HOURS ?? 6),
  databaseUrl: process.env.DATABASE_URL,
  redisUrl: process.env.REDIS_URL ?? "redis://localhost:6379",
  jobQueueConcurrency: Number(process.env.JOB_QUEUE_CONCURRENCY ?? 4),
};
